// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1STKTGPVbzVHJkSBK-wBhJAyTdCj4-hM',
    appId: '1:455736847212:web:548f12deedf544666a2149',
    messagingSenderId: '455736847212',
    projectId: 'acablocator',
    authDomain: 'acablocator.firebaseapp.com',
    storageBucket: 'acablocator.appspot.com',
    measurementId: 'G-LEYB0LY11C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuixiOy-STGYFp2IDQoZeVjmLvo155L_U',
    appId: '1:455736847212:android:32e5e9a01df9c34a6a2149',
    messagingSenderId: '455736847212',
    projectId: 'acablocator',
    storageBucket: 'acablocator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWLHl217xQIdIp0DkQpZaFTRFzHbuhkv0',
    appId: '1:455736847212:ios:247256bfb5c013de6a2149',
    messagingSenderId: '455736847212',
    projectId: 'acablocator',
    storageBucket: 'acablocator.appspot.com',
    iosClientId: '455736847212-q2qq5firv2r4t4tidfdvpd47j81psfr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.acabLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWLHl217xQIdIp0DkQpZaFTRFzHbuhkv0',
    appId: '1:455736847212:ios:247256bfb5c013de6a2149',
    messagingSenderId: '455736847212',
    projectId: 'acablocator',
    storageBucket: 'acablocator.appspot.com',
    iosClientId: '455736847212-q2qq5firv2r4t4tidfdvpd47j81psfr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.acabLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1STKTGPVbzVHJkSBK-wBhJAyTdCj4-hM',
    appId: '1:455736847212:web:6240aa7c20abc68a6a2149',
    messagingSenderId: '455736847212',
    projectId: 'acablocator',
    authDomain: 'acablocator.firebaseapp.com',
    storageBucket: 'acablocator.appspot.com',
    measurementId: 'G-T17RW1MP1E',
  );
}
